---
- name: Redefine libvirt network
  community.libvirt.virt_net:
    command: define
    name: "{{ libvirt_net_name }}"
    xml: "{{ lookup('template', 'network.xml.j2') }}"
    uri: "{{ libvirt_net_uri }}"

- name: Reload nftables isolation table
  ansible.builtin.command:
    cmd: "nft -f {{ libvirt_net_nft_rules_path }}"
  changed_when: true
